/**
 * The invoice viewer's ui:// resource: the HTML (with the app inlined; pdf.js is
 * not, it loads from the CDN at runtime) and the CSP it runs under.
 *
 * The HTML is generated by scripts/build-mcpapp.mjs. The Worker has no
 * filesystem, so there it is injected as a text module via
 * `setInvoicePdfAppHtml`; under Node it is read from dist/mcpapp.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Resource } from '@modelcontextprotocol/sdk/types.js';
import type { EnvRecord } from '../shared/env.js';
import { toolName } from '../spec/derive.js';
import {
  appCsp,
  appCspMeta,
  type AppCsp,
  INVOICE_PDF_APP_URI,
  INVOICE_PDF_OPERATION,
  MCP_APP_MIME,
} from './contract.js';

export const invoicePdfAppResource: Resource = {
  uri: INVOICE_PDF_APP_URI,
  name: 'Invoice viewer (PDF)',
  description:
    'Interactive panel that renders the invoice PDF. Opened by the host when ' +
    `${toolName(INVOICE_PDF_OPERATION)} is called.`,
  mimeType: MCP_APP_MIME,
};

let injectedHtml: string | null = null;

/** Inject the built HTML; the Worker bundle imports it as a text module. */
export function setInvoicePdfAppHtml(html: string): void {
  injectedHtml = html;
}

const HTML_CANDIDATES = [
  './mcpapp/invoice-pdf.html', // from dist/index.js
  '../../dist/mcpapp/invoice-pdf.html', // from src/mcpapp/*.ts under tsx
];

function resolveHtmlFromDisk(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));
  for (const candidate of HTML_CANDIDATES) {
    const path = resolve(here, candidate);
    if (existsSync(path)) return readFileSync(path, 'utf8');
  }
  return null;
}

/**
 * The viewer's HTML and CSP; `null` when the bundle has not been built.
 *
 * The CSP is built here, per read, because it names the deployment's own origin.
 */
export function readInvoicePdfApp(env?: EnvRecord): { html: string; csp: AppCsp } | null {
  const html = injectedHtml ?? resolveHtmlFromDisk();
  if (!html) return null;
  const csp = appCsp(env);
  return { html: withCspMeta(html, csp), csp };
}

/** Declare the CSP inside the document too, right after `<head>`. Idempotent. */
export function withCspMeta(html: string, csp: AppCsp): string {
  if (/http-equiv="Content-Security-Policy"/i.test(html)) return html;
  const meta = `<meta http-equiv="Content-Security-Policy" content="${appCspMeta(csp)}" />`;
  return html.replace(/<head>/i, `<head>\n${meta}`);
}
