/**
 * The invoice viewer's ui:// resource: the HTML (with the app inlined; pdf.js is
 * not, it loads from the CDN at runtime) and the CSP it runs under.
 *
 * The HTML is generated by scripts/build-mcpapp.mjs. The Worker has no
 * filesystem, so there it is injected as a text module via
 * `setInvoicePdfAppHtml`; under Node it is read from dist/mcpapp.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Resource } from '@modelcontextprotocol/sdk/types.js';
import { APP_CSP, INVOICE_PDF_APP_URI, MCP_APP_MIME } from './contract.js';

export const invoicePdfAppResource: Resource = {
  uri: INVOICE_PDF_APP_URI,
  name: 'Invoice viewer (PDF)',
  description:
    'Interactive panel that renders the invoice PDF. Opened by the host when ' +
    'beel_get_company_invoice_pdf is called.',
  mimeType: MCP_APP_MIME,
};

let injectedHtml: string | null = null;

/** Inject the built HTML; the Worker bundle imports it as a text module. */
export function setInvoicePdfAppHtml(html: string): void {
  injectedHtml = html;
}

const HTML_CANDIDATES = [
  './mcpapp/invoice-pdf.html', // from dist/index.js
  '../../dist/mcpapp/invoice-pdf.html', // from src/mcpapp/*.ts under tsx
];

function resolveHtmlFromDisk(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));
  for (const candidate of HTML_CANDIDATES) {
    const path = resolve(here, candidate);
    if (existsSync(path)) return readFileSync(path, 'utf8');
  }
  return null;
}

/** The viewer's HTML and CSP; `null` when the bundle has not been built. */
export function readInvoicePdfApp(): { html: string; csp: typeof APP_CSP } | null {
  const html = injectedHtml ?? resolveHtmlFromDisk();
  return html ? { html, csp: APP_CSP } : null;
}
